'use strict';

const {app, dialog, BrowserWindow, ipcMain, nativeImage} = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const {watch} = require('chokidar');
const fileUtil = require('./util/file');

const DEV_URL = 'http://127.0.0.1:1234';
const ICONS_DIR = path.join(__dirname, '..', 'build', 'assets', 'icons');
/** Pixel sizes generated by bin/assets.sh (icon-${size}.png). */
const ICON_SIZES = [16, 32, 48, 64, 128, 256, 512];
/** Logical 1x size for scaleFactor = size / ICON_BASE (Linux often uses only 1.0). */
const ICON_BASE = 128;

const WATCH_IGNORED = [
	/(^|[/\\])\../,
	'**/node_modules/**',
	'**/.git/**',
	'**/dist/**',
	'**/.parcel-cache/**',
	'**/artifacts/**'
];

let win = null;
let dirty = false;
let allowClose = false;
let watcher = null;

/** Multi-size app icon — ICO on Windows, PNG representations elsewhere. */
const loadAppIcon = () => {
	const icoPath = path.join(ICONS_DIR, 'icon.ico');
	if (process.platform === 'win32' && fs.existsSync(icoPath)) {
		const ico = nativeImage.createFromPath(icoPath);
		if (ico && !ico.isEmpty()) return ico;
	}

	// macOS dock / Linux: prefer a single high-res PNG (multi-rep is flaky for dock).
	if (process.platform === 'darwin' || process.platform === 'linux') {
		for (const size of [512, 256, 128, 1024]) {
			const filePath = path.join(ICONS_DIR, `icon-${size}.png`);
			if (!fs.existsSync(filePath)) continue;
			const img = nativeImage.createFromPath(filePath);
			if (img && !img.isEmpty()) return img;
		}
	}

	const image = nativeImage.createEmpty();
	for (const size of ICON_SIZES) {
		const filePath = path.join(ICONS_DIR, `icon-${size}.png`);
		if (!fs.existsSync(filePath)) continue;
		image.addRepresentation({
			scaleFactor: size / ICON_BASE,
			dataURL: `data:image/png;base64,${fs.readFileSync(filePath).toString('base64')}`
		});
	}
	return image.isEmpty() ? null : image;
};

const resolveStartUrl = () => {
	if (process.env.ELECTRON_START_URL) {
		return {type: 'url', value: process.env.ELECTRON_START_URL};
	}
	if (!app.isPackaged) {
		return {type: 'url', value: DEV_URL};
	}
	// Packaged: prefer app root (asar) so paths stay correct under electron/
	const indexHtml = path.join(app.getAppPath(), 'dist', 'index.html');
	return {type: 'file', value: indexHtml};
};

const stopWatch = () => {
	if (!watcher) return;
	watcher.close().catch(() => {});
	watcher = null;
};

const startWatch = rootPath => {
	stopWatch();
	if (!rootPath) return;
	watcher = watch(rootPath, {
		ignoreInitial: true,
		ignored: WATCH_IGNORED,
		awaitWriteFinish: {
			stabilityThreshold: 300,
			pollInterval: 100
		}
	});
	watcher.on('all', (event, filePath) => {
		if (!win || win.isDestroyed()) return;
		win.webContents.send('fs-change', {event, path: filePath});
	});
};

const selectRootFolder = async () => {
	const result = await dialog.showOpenDialog({
		title: 'Open Project Folder',
		properties: ['openDirectory']
	});
	if (result.canceled || !result.filePaths || !result.filePaths[0]) {
		return null;
	}
	const root = await fileUtil.openRoot(result.filePaths[0]);
	if (root && root.path) {
		startWatch(root.path);
	}
	return root;
};

const confirmDiscardIfDirty = async () => {
	if (!dirty || !win || win.isDestroyed()) return true;
	const {response} = await dialog.showMessageBox(win, {
		type: 'warning',
		buttons: ['Cancel', 'Discard'],
		defaultId: 0,
		cancelId: 0,
		title: 'Unsaved changes',
		message: 'You have unsaved changes. Discard and quit?'
	});
	return response === 1;
};

const requestClose = async () => {
	if (!(await confirmDiscardIfDirty())) return false;
	allowClose = true;
	stopWatch();
	if (win && !win.isDestroyed()) {
		win.close();
	}
	app.quit();
	return true;
};

const createWindow = () => {
	const icon = loadAppIcon();
	const browserWindow = new BrowserWindow({
		width: 1280,
		height: 800,
		show: false,
		frame: false,
		...(icon ? {icon} : {}),
		webPreferences: {
			devTools: true,
			preload: path.join(__dirname, 'preload.js'),
			contextIsolation: true,
			nodeIntegration: false,
			webSecurity: true
		}
	});

	browserWindow.once('ready-to-show', () => {
		if (icon && typeof browserWindow.setIcon === 'function') {
			browserWindow.setIcon(icon);
		}
		browserWindow.show();
	});

	browserWindow.on('close', e => {
		if (allowClose || !dirty) {
			stopWatch();
			return;
		}
		e.preventDefault();
		confirmDiscardIfDirty().then(ok => {
			if (!ok) return;
			allowClose = true;
			stopWatch();
			if (!browserWindow.isDestroyed()) browserWindow.close();
			app.quit();
		});
	});

	const start = resolveStartUrl();
	browserWindow.webContents.on('did-fail-load', (_e, code, desc, url) => {
		console.error('did-fail-load', {code, desc, url, start});
	});
	if (start.type === 'file') {
		if (!fs.existsSync(start.value)) {
			console.error('Packaged index missing:', start.value);
		}
		browserWindow.loadFile(start.value).catch(err => {
			console.error('Failed to load', start.value, err);
		});
	} else {
		browserWindow.loadURL(start.value).catch(err => {
			console.error('Failed to load', start.value, err);
		});
	}

	return browserWindow;
};

app.whenReady().then(() => {
	ipcMain.handle('selectRootFolder', () => selectRootFolder());
	ipcMain.handle('openRootFolder', async (_ev, dirPath) => {
		if (!dirPath || typeof dirPath !== 'string') return null;
		try {
			const root = await fileUtil.openRoot(dirPath);
			if (root && root.path) startWatch(root.path);
			return root;
		} catch (err) {
			console.error('openRootFolder failed', dirPath, err);
			return null;
		}
	});
	ipcMain.handle('listDir', (_ev, dirPath) => fileUtil.listDir(dirPath));
	ipcMain.handle('readFile', (_ev, filePath) => fileUtil.read(filePath));
	ipcMain.handle('readFileDataUrl', (_ev, filePath) => fileUtil.readDataUrl(filePath));
	ipcMain.handle('writeFile', (_ev, filePath, content) => fileUtil.write(filePath, content));
	ipcMain.handle('setDirty', (_ev, value) => {
		dirty = !!value;
		return dirty;
	});
	ipcMain.handle('minimize', () => {
		if (win) win.minimize();
	});
	ipcMain.handle('toggleMaximize', () => {
		if (!win) return false;
		if (win.isMaximized()) {
			win.unmaximize();
			return false;
		}
		win.maximize();
		return true;
	});
	ipcMain.handle('close', () => requestClose());

	const icon = loadAppIcon();
	// Dev / unpackaged: BrowserWindow.icon does not set the macOS Dock icon.
	if (icon && process.platform === 'darwin' && app.dock) {
		app.dock.setIcon(icon);
	}

	win = createWindow();

	app.on('activate', () => {
		if (BrowserWindow.getAllWindows().length === 0) {
			allowClose = false;
			win = createWindow();
		}
	});
});

app.on('window-all-closed', () => {
	stopWatch();
	if (process.platform !== 'darwin') app.quit();
});
