'use strict';

const {app, dialog, BrowserWindow, ipcMain, nativeImage} = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const fileUtil = require('./util/file');

const DEV_URL = process.env.ELECTRON_START_URL || 'http://127.0.0.1:1234';
const ICONS_DIR = path.join(__dirname, '..', 'build', 'assets', 'icons');
/** Pixel sizes generated by bin/assets.sh (icon-${size}.png). */
const ICON_SIZES = [16, 32, 48, 64, 128, 256, 512];
/** Logical 1x size for scaleFactor = size / ICON_BASE (Linux often uses only 1.0). */
const ICON_BASE = 128;

/** Multi-size app icon — ICO on Windows, PNG representations elsewhere. */
const loadAppIcon = () => {
	const icoPath = path.join(ICONS_DIR, 'icon.ico');
	if (process.platform === 'win32' && fs.existsSync(icoPath)) {
		const ico = nativeImage.createFromPath(icoPath);
		if (ico && !ico.isEmpty()) return ico;
	}

	const image = nativeImage.createEmpty();
	for (const size of ICON_SIZES) {
		const filePath = path.join(ICONS_DIR, `icon-${size}.png`);
		if (!fs.existsSync(filePath)) continue;
		image.addRepresentation({
			scaleFactor: size / ICON_BASE,
			dataURL: `data:image/png;base64,${fs.readFileSync(filePath).toString('base64')}`
		});
	}
	return image.isEmpty() ? null : image;
};

const selectRootFolder = async () => {
	const result = await dialog.showOpenDialog({
		title: 'Open Project Folder',
		properties: ['openDirectory']
	});
	if (result.canceled || !result.filePaths || !result.filePaths[0]) {
		return null;
	}
	return fileUtil.openRoot(result.filePaths[0]);
};

const createWindow = () => {
	const icon = loadAppIcon();
	const win = new BrowserWindow({
		width: 1280,
		height: 800,
		show: false,
		frame: false,
		...(icon ? {icon} : {}),
		webPreferences: {
			devTools: true,
			preload: path.join(__dirname, 'preload.js'),
			contextIsolation: true,
			nodeIntegration: false,
			webSecurity: true
		}
	});

	win.once('ready-to-show', () => {
		if (icon && typeof win.setIcon === 'function') {
			win.setIcon(icon);
		}
		win.show();
	});
	win.loadURL(DEV_URL).catch(err => {
		console.error('Failed to load', DEV_URL, err);
	});
	return win;
};

app.whenReady().then(() => {
	let win;

	ipcMain.handle('selectRootFolder', () => selectRootFolder());
	ipcMain.handle('listDir', (_ev, dirPath) => fileUtil.listDir(dirPath));
	ipcMain.handle('readFile', (_ev, filePath) => fileUtil.read(filePath));
	ipcMain.handle('readFileDataUrl', (_ev, filePath) => fileUtil.readDataUrl(filePath));
	ipcMain.handle('writeFile', (_ev, filePath, content) => fileUtil.write(filePath, content));
	ipcMain.handle('minimize', () => {
		if (win) win.minimize();
	});
	ipcMain.handle('toggleMaximize', () => {
		if (!win) return false;
		if (win.isMaximized()) {
			win.unmaximize();
			return false;
		}
		win.maximize();
		return true;
	});
	ipcMain.handle('close', () => {
		if (win) win.close();
		app.quit();
	});

	win = createWindow();

	app.on('activate', () => {
		if (BrowserWindow.getAllWindows().length === 0) {
			win = createWindow();
		}
	});
});

app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') app.quit();
});
