'use strict';

const {app, dialog, BrowserWindow, ipcMain, nativeImage, Menu} = require('electron');
const fs = require('fs');
const path = require('path');
const {watch} = require('chokidar');
const fileUtil = require('./util/file');

const bootLogPath = () => {
	try {
		return path.join(app.getPath('userData'), 'boot.log');
	} catch (err) {
		return path.join(require('os').tmpdir(), 'iblokz-boot.log');
	}
};
const bootLog = msg => {
	try {
		fs.appendFileSync(bootLogPath(), `[${new Date().toISOString()}] ${msg}\n`);
	} catch (err) { /* ignore */ }
};
bootLog(`start electron=${process.versions.electron} chrome=${process.versions.chrome} packaged=${app.isPackaged}`);

const electronMajorEarly = parseInt(String(process.versions.electron || '0').split('.')[0], 10) || 0;
if (electronMajorEarly > 0 && electronMajorEarly < 12) {
	// MacBookPro8,1 / Yosemite: Chromium 87 GPU process often never paints; load hangs.
	app.disableHardwareAcceleration();
	app.commandLine.appendSwitch('disable-gpu');
	app.commandLine.appendSwitch('disable-software-rasterizer');
	bootLog('legacy: disableHardwareAcceleration + disable-gpu');
}

const DEV_URL = 'http://127.0.0.1:1234';
const ICONS_DIR = path.join(__dirname, '..', 'build', 'assets', 'icons');
/** Pixel sizes generated by bin/assets.sh (icon-${size}.png). */
const ICON_SIZES = [16, 32, 48, 64, 128, 256, 512];
/** Logical 1x size for scaleFactor = size / ICON_BASE (Linux often uses only 1.0). */
const ICON_BASE = 128;

const WATCH_IGNORED = [
	/(^|[/\\])\../,
	'**/node_modules/**',
	'**/.git/**',
	'**/dist/**',
	'**/.parcel-cache/**',
	'**/artifacts/**'
];

let win = null;
let dirty = false;
let allowClose = false;
let watcher = null;

/** Multi-size app icon — ICO on Windows, PNG representations elsewhere. */
const loadAppIcon = () => {
	const icoPath = path.join(ICONS_DIR, 'icon.ico');
	if (process.platform === 'win32' && fs.existsSync(icoPath)) {
		const ico = nativeImage.createFromPath(icoPath);
		if (ico && !ico.isEmpty()) return ico;
	}

	// macOS dock / Linux: prefer a single high-res PNG (multi-rep is flaky for dock).
	if (process.platform === 'darwin' || process.platform === 'linux') {
		for (const size of [512, 256, 128, 1024]) {
			const filePath = path.join(ICONS_DIR, `icon-${size}.png`);
			if (!fs.existsSync(filePath)) continue;
			const img = nativeImage.createFromPath(filePath);
			if (img && !img.isEmpty()) return img;
		}
	}

	const image = nativeImage.createEmpty();
	for (const size of ICON_SIZES) {
		const filePath = path.join(ICONS_DIR, `icon-${size}.png`);
		if (!fs.existsSync(filePath)) continue;
		image.addRepresentation({
			scaleFactor: size / ICON_BASE,
			dataURL: `data:image/png;base64,${fs.readFileSync(filePath).toString('base64')}`
		});
	}
	return image.isEmpty() ? null : image;
};

const resolveStartUrl = () => {
	if (process.env.ELECTRON_START_URL) {
		return {type: 'url', value: process.env.ELECTRON_START_URL};
	}
	if (!app.isPackaged) {
		return {type: 'url', value: DEV_URL};
	}
	// Packaged: prefer app root (asar) so paths stay correct under electron/
	const indexHtml = path.join(app.getAppPath(), 'dist', 'index.html');
	return {type: 'file', value: indexHtml};
};

const stopWatch = () => {
	if (!watcher) return;
	watcher.close().catch(() => {});
	watcher = null;
};

const startWatch = rootPath => {
	stopWatch();
	if (!rootPath) return;
	watcher = watch(rootPath, {
		ignoreInitial: true,
		ignored: WATCH_IGNORED,
		awaitWriteFinish: {
			stabilityThreshold: 300,
			pollInterval: 100
		}
	});
	watcher.on('all', (event, filePath) => {
		if (!win || win.isDestroyed()) return;
		win.webContents.send('fs-change', {event, path: filePath});
	});
};

const isLegacyElectron = () => {
	const major = parseInt(String(process.versions.electron || '0').split('.')[0], 10) || 0;
	return major > 0 && major < 12;
};

/** Normalize Electron 6+ `{canceled,filePaths}` and older `string[]` return shapes. */
const pickOpenPaths = result => {
	if (result == null) return [];
	if (Array.isArray(result)) return result.filter(Boolean);
	if (result.canceled) return [];
	return Array.isArray(result.filePaths) ? result.filePaths.filter(Boolean) : [];
};

const selectRootFolder = async () => {
	const parent = win && !win.isDestroyed() ? win : undefined;
	// alwaysOnTop (legacy debug) buries NSOpenPanel behind the BrowserWindow.
	const wasOnTop = !!(parent && typeof parent.isAlwaysOnTop === 'function' && parent.isAlwaysOnTop());
	if (wasOnTop) parent.setAlwaysOnTop(false);
	if (parent) {
		try {
			parent.show();
			parent.focus();
		} catch (err) { /* ignore */ }
	}

	// Prefer home over macOS default (Documents) for "Open Project".
	const opts = {
		title: 'Open Project Folder',
		defaultPath: app.getPath('home'),
		properties: ['openDirectory', 'createDirectory']
	};

	bootLog('selectRootFolder: showing dialog');
	let result;
	try {
		// Sync dialog is more reliable on Electron 11 / Yosemite (promise + DevTools races).
		if (isLegacyElectron() && typeof dialog.showOpenDialogSync === 'function') {
			result = parent
				? dialog.showOpenDialogSync(parent, opts)
				: dialog.showOpenDialogSync(opts);
		} else {
			result = parent
				? await dialog.showOpenDialog(parent, opts)
				: await dialog.showOpenDialog(opts);
		}
	} catch (err) {
		bootLog(`selectRootFolder dialog error ${err && err.message ? err.message : err}`);
		console.error('selectRootFolder dialog failed', err);
		return null;
	} finally {
		if (wasOnTop && parent && !parent.isDestroyed()) parent.setAlwaysOnTop(true);
	}

	const filePaths = pickOpenPaths(result);
	bootLog(`selectRootFolder: paths=${JSON.stringify(filePaths)}`);
	if (!filePaths[0]) return null;

	const root = await fileUtil.openRoot(filePaths[0]);
	if (root && root.path) {
		startWatch(root.path);
	}
	return root;
};

const confirmDiscardIfDirty = async () => {
	if (!dirty || !win || win.isDestroyed()) return true;
	const {response} = await dialog.showMessageBox(win, {
		type: 'warning',
		buttons: ['Cancel', 'Discard'],
		defaultId: 0,
		cancelId: 0,
		title: 'Unsaved changes',
		message: 'You have unsaved changes. Discard and quit?'
	});
	return response === 1;
};

const requestClose = async () => {
	if (!(await confirmDiscardIfDirty())) return false;
	allowClose = true;
	stopWatch();
	if (win && !win.isDestroyed()) {
		win.close();
	}
	app.quit();
	return true;
};

const createWindow = () => {
	const icon = loadAppIcon();
	// Electron 11 / Yosemite: frameless + show:false often never surfaces a window
	// (ready-to-show may never fire if the renderer stalls on modern bundle syntax).
	const electronMajor = parseInt(String(process.versions.electron || '0').split('.')[0], 10) || 0;
	const legacyShell = electronMajor > 0 && electronMajor < 12;

	const browserWindow = new BrowserWindow({
		width: 1280,
		height: 800,
		show: legacyShell,
		// Legacy: native frame (frameless often never shows on 10.10). Modern: frameless.
		frame: legacyShell,
		...(icon ? {icon} : {}),
		webPreferences: {
			devTools: true,
			preload: path.join(__dirname, 'preload.js'),
			contextIsolation: true,
			nodeIntegration: false,
			webSecurity: true,
			spellcheck: false
		}
	});

	const reveal = () => {
		if (browserWindow.isDestroyed()) return;
		if (icon && typeof browserWindow.setIcon === 'function') {
			browserWindow.setIcon(icon);
		}
		if (!browserWindow.isVisible()) browserWindow.show();
		browserWindow.focus();
	};

	browserWindow.once('ready-to-show', reveal);
	// Fallback when ready-to-show never fires (common on older Electron).
	setTimeout(reveal, legacyShell ? 1500 : 4000);

	if (legacyShell) {
		// Auto-DevTools on load races first paint on Electron 11 (white screen until refresh).
		// Use View → Toggle DevTools, or ELECTRON_LEGACY_DEVTOOLS=1.
		if (process.env.ELECTRON_LEGACY_DEVTOOLS === '1') {
			try {
				browserWindow.webContents.openDevTools({mode: 'bottom'});
			} catch (err) {
				console.error('openDevTools failed', err);
				browserWindow.webContents.openDevTools();
			}
		}
		// Optional bring-to-front while debugging; leave off by default so
		// native open/save panels are not hidden behind the window.
		if (process.env.ELECTRON_LEGACY_ALWAYS_ON_TOP === '1') {
			browserWindow.setAlwaysOnTop(true);
		}
	}

	browserWindow.webContents.on('console-message', (_e, level, message, line, sourceId) => {
		const lineOut = `[renderer L${level}] ${message} (${sourceId}:${line})\n`;
		if (level >= 2) console.error(lineOut.trim());
		try {
			fs.appendFileSync(path.join(app.getPath('userData'), 'renderer.log'), lineOut);
		} catch (err) { /* ignore */ }
	});

	browserWindow.on('close', e => {
		if (allowClose || !dirty) {
			stopWatch();
			return;
		}
		e.preventDefault();
		confirmDiscardIfDirty().then(ok => {
			if (!ok) return;
			allowClose = true;
			stopWatch();
			if (!browserWindow.isDestroyed()) browserWindow.close();
			app.quit();
		});
	});

	const start = resolveStartUrl();
	bootLog(`createWindow start=${JSON.stringify(start)} legacyShell=${legacyShell}`);
	browserWindow.webContents.on('dom-ready', () => {
		bootLog('dom-ready');
		browserWindow.webContents.executeJavaScript(`
			window.addEventListener('error', function (e) {
				window.__iblokzErr = String(e.message || e.error || e);
			});
			window.addEventListener('unhandledrejection', function (e) {
				window.__iblokzErr = String((e.reason && e.reason.message) || e.reason || e);
			});
			true
		`).catch(err => bootLog(`dom-ready inject failed ${err}`));
	});
	browserWindow.webContents.on('did-fail-load', (_e, code, desc, url) => {
		bootLog(`did-fail-load code=${code} desc=${desc} url=${url}`);
		console.error('did-fail-load', {code, desc, url, start});
		reveal();
	});
	browserWindow.webContents.on('did-finish-load', () => {
		bootLog('did-finish-load');
		browserWindow.webContents.executeJavaScript(
			`({href: location.href, bodyKids: document.body ? document.body.children.length : -1, title: document.title, scripts: document.scripts.length, err: window.__iblokzErr || null})`
		).then(info => {
			bootLog(`page ${JSON.stringify(info)}`);
		}).catch(err => bootLog(`executeJavaScript failed ${err}`));
		reveal();
	});
	if (start.type === 'file') {
		bootLog(`loadFile exists=${fs.existsSync(start.value)} path=${start.value}`);
		if (!fs.existsSync(start.value)) {
			console.error('Packaged index missing:', start.value);
			bootLog('Packaged index missing');
		}
		browserWindow.loadFile(start.value).catch(err => {
			bootLog(`loadFile catch ${err}`);
			console.error('Failed to load', start.value, err);
			reveal();
		});
	} else {
		browserWindow.loadURL(start.value).catch(err => {
			bootLog(`loadURL catch ${err}`);
			console.error('Failed to load', start.value, err);
			reveal();
		});
	}

	return browserWindow;
};

const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
	app.quit();
} else {
	app.on('second-instance', () => {
		if (!win || win.isDestroyed()) return;
		if (win.isMinimized()) win.restore();
		win.show();
		win.focus();
	});

	app.whenReady().then(() => {
		ipcMain.handle('selectRootFolder', () => selectRootFolder());
		ipcMain.handle('openRootFolder', async (_ev, dirPath) => {
			if (!dirPath || typeof dirPath !== 'string') return null;
			try {
				const root = await fileUtil.openRoot(dirPath);
				if (root && root.path) startWatch(root.path);
				return root;
			} catch (err) {
				console.error('openRootFolder failed', dirPath, err);
				return null;
			}
		});
		ipcMain.handle('listDir', (_ev, dirPath) => fileUtil.listDir(dirPath));
		ipcMain.handle('readFile', (_ev, filePath) => fileUtil.read(filePath));
		ipcMain.handle('readFileDataUrl', (_ev, filePath) => fileUtil.readDataUrl(filePath));
		ipcMain.handle('writeFile', (_ev, filePath, content) => fileUtil.write(filePath, content));
		ipcMain.handle('setDirty', (_ev, value) => {
			dirty = !!value;
			return dirty;
		});
		ipcMain.handle('minimize', () => {
			if (win) win.minimize();
		});
		ipcMain.handle('toggleMaximize', () => {
			if (!win) return false;
			if (win.isMaximized()) {
				win.unmaximize();
				return false;
			}
			win.maximize();
			return true;
		});
		ipcMain.handle('close', () => requestClose());

		const icon = loadAppIcon();
		// Dev / unpackaged: BrowserWindow.icon does not set the macOS Dock icon.
		if (icon && process.platform === 'darwin' && app.dock) {
			app.dock.setIcon(icon);
		}

		const electronMajor = parseInt(String(process.versions.electron || '0').split('.')[0], 10) || 0;
		const openProjectItem = {
			label: 'Open Project…',
			accelerator: 'CmdOrCtrl+O',
			click: () => {
				if (!win || win.isDestroyed()) return;
				win.webContents.send('open-folder-request');
			}
		};
		const menuTemplate = [
			{
				label: app.name || 'iBloKz IDE',
				submenu: [
					{role: 'about'},
					{type: 'separator'},
					{role: 'quit'}
				]
			},
			{
				label: 'File',
				submenu: [openProjectItem]
			},
			{
				label: 'Edit',
				submenu: [
					{role: 'undo'},
					{role: 'redo'},
					{type: 'separator'},
					{role: 'cut'},
					{role: 'copy'},
					{role: 'paste'},
					{role: 'selectall'}
				]
			},
			{
				label: 'View',
				submenu: [
					{role: 'reload'},
					{role: 'toggledevtools'},
					{type: 'separator'},
					{role: 'togglefullscreen'}
				]
			}
		];
		// Always set File → Open Project so Cmd/Ctrl+O works (renderer hotkey defers to this).
		Menu.setApplicationMenu(Menu.buildFromTemplate(menuTemplate));
		if (electronMajor > 0 && electronMajor < 12) {
			bootLog('legacy: application menu set');
		}

		win = createWindow();

		app.on('activate', () => {
			if (BrowserWindow.getAllWindows().length === 0) {
				allowClose = false;
				win = createWindow();
			}
		});
	});

	app.on('window-all-closed', () => {
		stopWatch();
		if (process.platform !== 'darwin') app.quit();
	});
}
