---
Mod+O: project.openFolder
Mod+F: openFind
Mod+P: openFileSearch
"Mod+/": editor.toggleComment
Mod+Tab: nextTab
Mod+Shift+Tab: prevTab
Mod+PageDown: nextTab
Mod+PageUp: prevTab
Mod+B: layout.toggle leftSideBar
Mod+Shift+B: layout.toggle rightSideBar
Mod+J: layout.toggle bottomPanel
Mod+Shift+P: layout.toggle preview
